import { motion as Motion } from 'framer-motion'
import { ArrowUp, ArrowUpRight, Award, BadgeCheck, Bot, Box, BrainCircuit, BriefcaseBusiness, Building2, CalendarDays, ChartNoAxesColumnIncreasing, Compass, Github, GraduationCap, Languages, Linkedin, Mail, MapPin, Sparkles, Target } from 'lucide-react'
import { expertise, experience, profile, skillGroups } from '../data/content'
import IconChip from './IconChip'

const iconMap = { Target, BrainCircuit, ChartNoAxesColumnIncreasing, Box, Compass, Bot, BriefcaseBusiness }
const capabilityIcons = [Target, Compass, BrainCircuit, Box, BriefcaseBusiness]
const credentialIcons = [BrainCircuit, Target, Award]

const Reveal = ({children,className=''}) => <Motion.div className={className} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.5}}>{children}</Motion.div>

export function Expertise() { return <section className="expertise-strip section-pad core-strengths" aria-labelledby="strengths-heading"><div className="strengths-heading"><div><span className="kicker">CORE STRENGTHS</span><h2 id="strengths-heading">Where strategy meets <em>execution.</em></h2></div><p>Four connected capabilities that move an AI product from opportunity to measurable impact.</p></div><div className="strengths-grid">{expertise.map((item,index)=>{const Icon=iconMap[item.icon];return <Motion.article className={`strength-card strength-tone-${index+1}`} key={item.title} initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} whileHover={{y:-6}} whileTap={{scale:.985}} viewport={{once:true,amount:.2}} transition={{duration:.4,delay:index*.07,ease:[.22,1,.36,1]}}><div className="strength-card-top"><div className="strength-icon"><Icon/></div><span>FOCUS AREA</span><Sparkles aria-hidden="true"/></div><h3>{item.title}</h3><p>{item.text}</p><div className="strength-card-footer" aria-hidden="true"><i></i><span></span></div></Motion.article>})}</div></section> }

export function About() { const pillars=[['Compass','Product Thinking','Discovery, roadmaps, prioritization, PRDs, user stories and stakeholder alignment.'],['Bot','AI Product Development','Generative AI, agentic workflows, RAG architecture, prompt engineering and LLM integration.'],['BriefcaseBusiness','Business Execution','Founder experience, customer research, process improvement and end-to-end delivery.']]; return <section id="about" className="section-pad content-section about-section"><Reveal className="section-heading"><div><span className="kicker">ABOUT</span><h2>Strategy with <em>builder energy.</em></h2></div><p>Product discovery, stakeholder alignment and hands-on AI development—brought together to create products people can actually use.</p></Reveal><div className="about-story"><Reveal className="about-statement"><div className="about-statement-label"><Sparkles/><span>PRODUCT + AI + EXECUTION</span></div><h3>From business problem to <em>working product.</em></h3><p>I am a product-focused professional with more than four years of experience spanning enterprise technology, supply-chain transformation and entrepreneurship. I design AI-powered products, intelligent agents, RAG applications and automation workflows that turn business requirements into scalable, customer-focused solutions.</p><div className="about-statement-footer"><span>Discover thoughtfully</span><i></i><span>Build practically</span><i></i><span>Deliver clearly</span></div></Reveal><Reveal className="about-process"><span className="kicker">HOW I WORK</span><div className="process-list"><article><div><Compass/></div><span><strong>Discover</strong><small>Understand users, constraints and outcomes.</small></span></article><article><div><Bot/></div><span><strong>Build</strong><small>Shape AI workflows and useful product experiences.</small></span></article><article><div><BriefcaseBusiness/></div><span><strong>Deliver</strong><small>Align stakeholders and move from concept to impact.</small></span></article></div></Reveal></div><div className="about-pillars">{pillars.map(([icon,title,text],index)=>{const Icon=iconMap[icon];return <Reveal className={`about-pillar about-tone-${index+1}`} key={title}><div className="pillar-icon"><Icon/></div><Sparkles className="pillar-spark" aria-hidden="true"/><h3>{title}</h3><p>{text}</p><div className="pillar-line" aria-hidden="true"><i></i></div></Reveal>})}</div></section> }

export function Experience() { return <section id="experience" className="section-pad content-section experience-section"><div className="section-heading"><div><span className="kicker">EXPERIENCE</span><h2>A track record of <em>execution.</em></h2></div><p>Building useful products at the intersection of entrepreneurship, enterprise transformation and applied AI.</p></div><div className="career-journey">{experience.map((item,index)=><Reveal className={`experience-entry tone-${index+1}`} key={item.role}><div className="journey-rail" aria-hidden="true"><span></span></div><article className="experience-card"><div className="experience-card-top"><div className="company-mark" aria-hidden="true"><Building2/></div><div className="experience-title"><span className="role-label">{index===0?'CURRENT FOCUS':'CAREER CHAPTER'}</span><h3>{item.role}</h3><h4>{item.company}</h4></div><Sparkles className="experience-spark" aria-hidden="true"/></div><div className="experience-facts"><span><CalendarDays/>{item.date}</span><span><MapPin/>{item.place}</span></div><ul className="experience-outcomes">{item.bullets.map(bullet=><li key={bullet}><span aria-hidden="true"><ArrowUpRight/></span><p>{bullet}</p></li>)}</ul></article></Reveal>)}</div></section> }

export function Skills() { return <section id="skills" className="section-pad content-section capabilities-section"><div className="section-heading"><div><span className="kicker">CAPABILITIES</span><h2>Product sense, <em>technical depth.</em></h2></div><p>A practical toolkit for discovering, defining and delivering AI products—from customer insight to production-ready systems.</p></div><div className="capability-grid">{skillGroups.map(([title,skills],index)=>{const Icon=capabilityIcons[index];return <Reveal className={`capability-card capability-tone-${index+1}`} key={title}><div className="capability-card-head"><div className="capability-icon"><Icon/></div><div><span>CORE EXPERTISE</span><h3>{title}</h3></div><Sparkles className="capability-spark" aria-hidden="true"/></div><div className="capability-rule" aria-hidden="true"><i></i></div><div className="capability-chips">{skills.map(skill=><IconChip label={skill} key={skill}/>)}</div></Reveal>})}</div></section> }

export function Credentials() { const certificates=[['Generative AI & Agentic AI','DigiDARA Technologies',['LLMs','Multi-Agent Systems','RAG','AI Automation']],['AI Product Management','IBM, via AcceleratorX',['AI PRDs','Product Fundamentals','No-Code Development']],['SAP S/4HANA Certified Associate','SAP',['Sourcing and Procurement']]]; return <section className="section-pad content-section credentials-section"><div className="section-heading"><div><span className="kicker">CREDENTIALS</span><h2>Learning that <em>compounds.</em></h2></div><p>Focused learning across AI product leadership, agentic systems and enterprise operations.</p></div><div className="credential-showcase">{certificates.map(([title,issuer,topics],index)=>{const Icon=credentialIcons[index];return <Reveal className={`credential-card credential-tone-${index+1}`} key={title}><div className="credential-card-top"><div className="credential-icon"><Icon/></div><span>CERTIFICATION</span><BadgeCheck aria-label="Credential entry"/></div><div className="credential-card-body"><h3>{title}</h3><p>Issued by <strong>{issuer}</strong></p><div className="credential-topics">{topics.map(topic=><IconChip label={topic} key={topic}/>)}</div></div></Reveal>})}</div><div className="credential-details"><Reveal className="credential-detail-card education-card"><div className="detail-card-heading"><div><GraduationCap/></div><span>EDUCATION</span></div><div className="education-list"><article><i></i><div><h3>M.Sc. Supply Chain & Purchasing</h3><p>Skema Business School</p><small>Paris, France</small></div></article><article><i></i><div><h3>B.Tech. Mechanical Engineering</h3><p>SASTRA University</p><small>Tamil Nadu, India</small></div></article></div></Reveal><Reveal className="credential-detail-card languages-card"><div className="detail-card-heading"><div><Languages/></div><span>LANGUAGES</span></div><div className="language-cards"><span><strong>English</strong></span><span><strong>French</strong><small>B1</small></span><span><strong>Tamil</strong><small>Native</small></span><span><strong>Hindi</strong><small>Beginner</small></span></div></Reveal></div></section> }

export function Contact() { return <section id="contact" className="section-pad contact"><span className="kicker">LET'S WORK TOGETHER</span><h2>Let’s build useful<br/><em>AI products.</em></h2><p>I’m interested in AI product management, product-builder and agentic AI opportunities where product thinking and hands-on execution are equally important.</p><div className="contact-actions"><a className="button primary" href={profile.emailUrl} target="_blank" rel="noopener noreferrer">Email me <ArrowUpRight/></a><a className="button secondary" href={profile.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn <Linkedin/></a><a className="button secondary" href={profile.github} target="_blank" rel="noopener noreferrer">GitHub <Github/></a></div></section> }

export function Footer() { return <footer className="site-footer"><div className="footer-main"><div className="footer-brand"><a className="logo" href="#home" aria-label="Sanmuga Piriyan home">SP<span>.</span></a><h2>AI Product Manager<br/><em>& Product Builder</em></h2><p>Turning complex business problems into practical, customer-focused AI products.</p><div className="footer-status"><Sparkles/><span>Open to AI Product opportunities</span></div></div><nav className="footer-nav" aria-label="Footer navigation"><span>EXPLORE</span><a href="#about">About</a><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#skills">Capabilities</a></nav><div className="footer-connect"><span>CONNECT</span><a href={profile.emailUrl} target="_blank" rel="noopener noreferrer"><Mail/><div><small>Email</small><strong>{profile.email}</strong></div><ArrowUpRight/></a><a href={profile.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin/><div><small>LinkedIn</small><strong>Sanmuga Piriyan</strong></div><ArrowUpRight/></a><a href={profile.github} target="_blank" rel="noopener noreferrer"><Github/><div><small>GitHub</small><strong>piriyan46-png</strong></div><ArrowUpRight/></a></div></div><div className="footer-bottom"><p className="footer-copyright">© {new Date().getFullYear()} Sanmuga Piriyan</p><div className="footer-meta"><span><MapPin/> Bengaluru, India</span><i aria-hidden="true"></i><span>Designed and built with React</span></div><a className="back-to-top" href="#home" aria-label="Back to top">Back to top <ArrowUp/></a></div></footer> }
